defaults:
  - schema
  - _self_

# model attributes
base_model: gine
pe_method: masked_sign_inv
n_node_types: 1   # based on https://github.com/pyg-team/pytorch_geometric/files/7494194/README.txt
n_edge_types: 1
node_emb_dims: 85
pooling: add

phi_model_name: gin
pe_dims: 30   # based on SignNet and BasisNet paper (Table 1)
n_phi_layers: 4
phi_hidden_dims: 85
psi_model_name: zero
n_psis: 8
n_psi_layers: 4
psi_hidden_dims: 85
psi_activation: relu
num_heads: 4
pe_aggregate: add

n_base_layers: 4
base_hidden_dims: 85

n_mlp_layers: 3
mlp_hidden_dims: 85
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: relu
mlp_dropout_prob: 0.0

residual: true
graph_norm: false
batch_norm: false

# data attributes
use_subset: true
train_batch_size: 128
val_batch_size: 128

# optimizer attributes
lr: 1e-3
weight_decay: 1e-4
momentum: 0.9
nesterov: false

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 600
out_dirpath: out/baseline
