defaults:
  - schema
  - _self_

# model attributes
# base_model: [gine, pna]
base_model: gine
# pe_method: [none, sign_inv, basis_inv, spe, masked_sign_inv, masked_spe]
pe_method: id
n_node_types: 39   # based on https://github.com/pyg-team/pytorch_geometric/files/7494194/README.txt
n_edge_types: 10
node_emb_dims: 64
pooling: add

# phi_model_name: [gin, gin_deepsets, ppgn, mlp, zero]
phi_model_name: mlp
pe_dims: 32   # based on SignNet and BasisNet paper (Table 1)
n_phi_layers: 8
phi_hidden_dims: 16
# psi_model_name: [mlp, deepsets, transformer, masked_deepsets, zero]
psi_model_name: mlp
n_psis: 16
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: peg

n_base_layers: 4
base_hidden_dims: 64

n_mlp_layers: 3
mlp_hidden_dims: 64
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: relu
mlp_dropout_prob: 0.0

residual: true
batch_norm: false
graph_norm: false

# data attributes
use_subset: true
train_batch_size: 64
val_batch_size: 64

# optimizer attributes
lr: 1e-4
weight_decay: 0
momentum: 0.9
nesterov: false

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 100
out_dirpath: out/baseline
